---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Chart.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Chart.name | nindent 4 }}
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
          - name: {{ .Chart.name }}-data
            mountPath: /data
      volumes:
      - name: {{ .Chart.name }}-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Chart.name }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
